package ru.kpfu.itis.rodsher.dto;

public enum Status {
    FILE_DOWNLOAD_SUCCESS,
    FILE_DOWNLOAD_SAVING_ERROR,
    FILE_DOWNLOAD_DB_ERROR,
    FILE_UPLOAD_SUCCESS,
    FILE_UPLOAD_ERROR,
    USER_REG_SUCCESS,
    USER_REG_ERROR,
    USER_LOGIN_NO_SUCH_USER,
    USER_LOGIN_WRONG_PASSWORD,
    USER_LOGIN_NOT_VERIFIED,
    USER_LOGIN_SUCCESS,
    USER_VERIF_SUCCESS,
    USER_VERIF_EXPIRED,
    USER_VERIF_EMPTY,
}
