package ru.kpfu.itis.rodsher.dto;

public enum Status {
    USER_SIGN_IN_SUCCESS,
    USER_SIGN_IN_ERROR,
    USER_REG_SUCCESS,
    USER_REG_ERROR,
    USER_LOAD_SUCCESS,
    USER_LOAD_ERROR,
    ARTICLE_LOAD_SUCCESS,
    ARTICLE_LOAD_ERROR,
    ARTICLE_DELETE_SUCCESS,
    ARTICLE_DELETE_ERROR,
    ARTICLE_LOAD_BY_USER_ID_SUCCESS,
    ARTICLE_LOAD_BY_USER_ID_ERROR,
    ARTICLE_ADD_SUCCESS,
    ARTICLE_ADD_ERROR
}
