package ru.kpfu.itis.rodsher.jlmq.dto;

public enum Status {
    MESSAGE_PRODUCE_NO_QUEUE_ERROR,
    MESSAGE_PRODUCE_PAYLOAD_PARSE_ERROR,
    MESSAGE_PRODUCE_SUCCESS,

    CONSUMER_SUBSCRIBE_ALREADY_EXISTS_ERROR,
    CONSUMER_SUBSCRIBE_NO_QUEUE_ERROR,
    CONSUMER_SUBSCRIBE_SUCCESS,

    MESSAGE_UPDATE_STATUS_ERROR,
    MESSAGE_UPDATE_STATUS_SUCCESS,

    QUEUE_CREATE_ERROR,
    QUEUE_CREATE_SUCCESS,

    MESSAGE_FIND_AVAILABLE_NO_QUEUE_ERROR,
    MESSAGE_FIND_AVAILABLE_NO_ERROR,
    MESSAGE_FIND_AVAILABLE_SUCCESS,

    MESSAGE_SEND_TO_CONSUMER_NO_CONSUMER_ERROR,
    MESSAGE_SEND_TO_CONSUMER_UNAVAILABLE_ERROR,
    MESSAGE_SEND_TO_CONSUMER_NO_MESSAGE_ERROR,
    MESSAGE_SEND_TO_CONSUMER_SEND_ERROR,
    MESSAGE_SEND_TO_CONSUMER_SUCCESS,

    MESSAGE_FIND_BY_ID_NO_ERROR,
    MESSAGE_FIND_BY_ID_SUCCESS,

    CONSUMER_COMPLETE_MESSAGE_NO_MESSAGE_ERROR,
    CONSUMER_COMPLETE_MESSAGE_SUCCESS,

    CONSUMER_ACCEPT_MESSAGE_NO_MESSAGE_ERROR,
    CONSUMER_ACCEPT_MESSAGE_SUCCESS,

    MESSAGE_SEND_SUCCESS,
    MESSAGE_SEND_ERROR
}
